### ISSUE TITLE
Implementation for DAI and GScore

### ISSUE THREAD

**Issue by Georgefwt** [zewei-Zhang/GoodDrag#1]
The paper mentioned DAI and GScore as evaluation metrics. Would it be possible for the author to share the official implementation of these metrics?

**Comment by zewei-Zhang** [comment]
Thank you for your interest in our paper and for inquiring about the DAI and GScore evaluation. I have updated the repository with the official implementation of these metrics. You can find the updated files in the **evaluation** directory.

**Comment by Georgefwt** [comment]
Thank you for getting back to me so quickly! Much appreciated!
